name: Pull Request Check # 워크플로우 이름(자동화 시키는 이름)

on: # 워크플로우 실행 트리거(실행 환경)
  pull_request: # pull_request가 실행 될때만 실행되게 하기.
    types: [opened, synchronize] # pull_request가 열릴 때나, 업데이트 될 때
    

jobs: # 작업 정의
  check: #작업 전 확인
    runs-on: ubuntu-lastest #우분투 환경
    permissions: #권한 설정
      pull-requests: write #PR에 쓰기 권한 설정
    steps: # 작업 단계
      - uses: actions/github-script@v7
        with: 
          script: | #스크립트 시작
          const pull_request = context.payload.pull_request; # pull_request 객체 가져오기

          if (pull_request === undefined) { # pull_request가 없는 경우
              console.log("This is not a pull request"); # "This is not a pull request" 출력
              return; # 종료
          }

          const body = pull_request.body;

          if(!body){
            // PR에 코멘트를 추가
            await github.rest.issues.createComment({ // PR에 코멘트 추가
              owner: context.repo.owner, // 저장소 소유자
              repo: context.repo.repo, // 저장소 이름
              issue_number: pull_request.number, // PR 번호
              body: "해당 PR은 가이드라인을 준수하지 않음", // 코맨트 내용
            });

            // PR 닫기
            await github.rest.pulls.update({ // PR을 닫음
              owner: context.repo.owner, // 저장소 소유자
              repo: context.repo.repo, // 저장소 이름
              pull_number: pull_request.number, // PR 번호
              state: "closed", // 상태를 닫힘으로 변경
            
          }
              
